### ISSUE TITLE
docker 部署,重启后,无法登陆 api/login 

### ISSUE THREAD

**Issue by MichaelGzy** [xinliangnote/go-gin-api#39]
{"level":"error","time":"2021-05-27 13:23:30","caller":"core/core.go:359","msg":"got panic","domain":"go-gin-api[fat]","panic":"runtime error: invalid memory address or nil pointer dereference","stack":"goroutine 61 [running]:\nruntime/debug.Stack(0xc0015d3060, 0x105bd40, 0x2ac2670)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/xinliangnote/go-gin-api/internal/pkg/core.New.func2.1(0xc00042a4e0, 0x135d7a0, 0xc0000a8f10, 0xc001596270, 0xc00038a0f0, 0xc023e9148ea4ccca, 0x1148be54cd, 0x2aded00)\n\t/app/internal/pkg/core/core.go:358 +0x19f3\npanic(0x105bd40, 0x2ac2670)\n\t/usr/local/go/src/runtime/panic.go:969 +0x1b9\ngithub.com/xinliangnote/go-gin-api/internal/api/service/authorized_service.(*service).DetailByKey(0xc001598680, 0x135d7a0, 0xc0000a8f08, 0xc00159c280, 0x5, 0x1, 0xc001599940, 0x2)\n\t/app/internal/api/service/authorized_service/service_detailbykey.go:31 +0x132\ngithub.com/xinliangnote/go-gin-api/internal/router/middleware.(*middleware).Signature.func1(0x135d7a0, 0xc0000a8f08)\n\t/app/internal/router/middleware/middle_signature.go:60 +0x724\ngithub.com/xinliangnote/go-gin-api/internal/pkg/core.wrapHandlers.func1(0xc00038a0f0)\n\t/app/internal/pkg/core/core.go:214 +0xad\ngithub.com/gin-gonic/gin.(*Context).Next(0xc00038a0f0)\n\t/app/vendor/github.com/gin-gonic/gin/context.go:161 +0x3b\ngithub.com/xinliangnote/go-gin-api/internal/pkg/core.New.func3(0xc00038a0f0)\n\t/app/internal/pkg/core/core.go:505 +0x1b0\ngithub.com/gin-gonic/gin.(*Context).Next(0xc00038a0f0)\n\t/app/vendor/github.com/gin-gonic/gin/context.go:161 +0x3b\ngithub.com/xinliangnote/go-gin-api/internal/pkg/core.New.func2(0xc00038a0f0)\n\t/app/internal/pkg/core/core.go:487 +0x210\ngithub.com/gin-gonic/gin.(*Context).Next(0xc00038a0f0)\n\t/app/vendor/github.com/gin-gonic/gin/context.go:161 +0x3b\ngithub.com/xinliangnote/go-gin-api/internal/pkg/core.New.func1(0xc00038a0f0)\n\t/app/internal/pkg/core/core.go:336 +0x52\ngithub.com/gin-gonic/gin.(*Context).Next(0xc00038a0f0)\n\t/app/vendor/github.com/g
+0x3b\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0004383c0, 0xc00038a0f0)\n\t/app/vendor/github.com/gin-gonic/gin/gin.go:409 +0x67a\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0004383c0, 0x1342740, 0xc000444460, 0xc00032f600)\n\t/app/vendor/github.com/gin-gonic/gin/gin.go:367 +0x14d\ngithub.com/xinliangnote/go-gin-api/internal/pkg/core.(*mux).ServeHTTP(0xc0000a8060, 0x1342740, 0xc000444460, 0xc00032f600)\n\t/app/internal/pkg/core/core.go:234 +0x4c\nnet/http.serverHandler.ServeHTTP(0xc0004440e0, 0x1342740, 0xc000444460, 0xc00032f600)\n\t/usr/local/go/src/net/http/server.go:2843 +0xa3\nnet/http.(*conn).serve(0xc000436640, 0x1345bc0, 0xc0003d5c80)\n\t/usr/local/go/src/net/http/server.go:1925 +0x8ad\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2969 +0x36c\n"}
{"level":"error","time":"2021-05-27 13:23:30","caller":"notify/notify.go:15","msg":"Mail config error","domain":"go-gin-api[fat]"}

**Comment by MichaelGzy** [comment]
it's ok ,a few moment later,i did kown what i have done.
